<?php

namespace Database\Seeders;

use App\Models\Constant\Keturunan;
use Illuminate\Database\Seeder;

class KodKeturunanSeeder extends Seeder
{
    public function run()
    {
        // check if table kod keturunan is empty
        if (Keturunan::get()->count() == 0) {

            Keturunan::insert([
                ['kod_keturunan' => '0100', 'keturunan' => 'MELAYU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0101', 'keturunan' => 'BUGIS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0102', 'keturunan' => 'BOYAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0103', 'keturunan' => 'BANJAR', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0104', 'keturunan' => 'JAWA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0105', 'keturunan' => 'JAWI PEKAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0106', 'keturunan' => 'MINANGKABAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0200', 'keturunan' => 'CINA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0201', 'keturunan' => 'CANTONESE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0202', 'keturunan' => 'FOOCHOW', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0203', 'keturunan' => 'HAINANESE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0204', 'keturunan' => 'HENGHUA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0205', 'keturunan' => 'HOKCHIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0206', 'keturunan' => 'HOKCHIU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0207', 'keturunan' => 'HOKKIEN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0208', 'keturunan' => 'KHEK (HAKKA)', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0209', 'keturunan' => 'KWONGSAI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0210', 'keturunan' => 'TEOCHEW', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0211', 'keturunan' => 'KONGFOO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0212', 'keturunan' => 'HYLAM', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0213', 'keturunan' => 'KENGCHU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0214', 'keturunan' => 'KOCHOU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0300', 'keturunan' => 'INDIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0301', 'keturunan' => 'MALAYALI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0302', 'keturunan' => 'PUNJABI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0303', 'keturunan' => 'SIKH', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0304', 'keturunan' => 'TAMIL', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0305', 'keturunan' => 'TELEGU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0306', 'keturunan' => 'MALABARI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0307', 'keturunan' => 'INDIA MUSLIM', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0308', 'keturunan' => 'TELUGU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0309', 'keturunan' => 'ORISSA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0400', 'keturunan' => 'BANGLADESHI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0500', 'keturunan' => 'PAKISTANI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0600', 'keturunan' => 'SRI LANKA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0601', 'keturunan' => 'TAMIL SRI LANKA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0602', 'keturunan' => 'MELAYU SRI LANKA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0603', 'keturunan' => 'SINHALESE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0604', 'keturunan' => 'CEYLONESE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0700', 'keturunan' => 'INDONESIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0701', 'keturunan' => 'TIDUNG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0800', 'keturunan' => 'ETNIK SABAH', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0801', 'keturunan' => 'BAJAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0802', 'keturunan' => 'DUSUN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0803', 'keturunan' => 'KADAZAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0804', 'keturunan' => 'MURUT', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0805', 'keturunan' => 'SINO-NATIVE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0806', 'keturunan' => 'SULUK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0807', 'keturunan' => 'TIDUNG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0901', 'keturunan' => 'BINADAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0902', 'keturunan' => 'BISAYA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0903', 'keturunan' => 'BONGOL', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0904', 'keturunan' => 'BRUNEI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0905', 'keturunan' => 'DUMPAS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0906', 'keturunan' => 'IRANUN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0907', 'keturunan' => 'IDAHAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0908', 'keturunan' => 'KWIJAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0909', 'keturunan' => 'KEDAYAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0910', 'keturunan' => 'LINGKABAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0911', 'keturunan' => 'LUNDAYEH', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0912', 'keturunan' => 'LASAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0913', 'keturunan' => 'MELANAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0914', 'keturunan' => 'MANGKAAK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0915', 'keturunan' => 'MATAGANG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0916', 'keturunan' => 'MINOKOK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0917', 'keturunan' => 'MELAYU SABAH', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0918', 'keturunan' => 'MOMOGUN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0919', 'keturunan' => 'PAITAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0920', 'keturunan' => 'RUMANAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0921', 'keturunan' => 'RUNGUS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0922', 'keturunan' => 'SUNGAI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0923', 'keturunan' => 'SONSONGAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0924', 'keturunan' => 'SINULIHAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0925', 'keturunan' => 'TOMBONUO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0926', 'keturunan' => 'TAGAL', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0927', 'keturunan' => 'TINAGAS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0928', 'keturunan' => 'COCOS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0929', 'keturunan' => 'KIMARAGANG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0930', 'keturunan' => 'BOLONGAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0931', 'keturunan' => 'BUTON', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0932', 'keturunan' => 'KAGAYAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0933', 'keturunan' => 'BALABAK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0934', 'keturunan' => 'KADAZAN-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0935', 'keturunan' => 'DUSUN-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0936', 'keturunan' => 'BAJAU-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0937', 'keturunan' => 'MURUT-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0938', 'keturunan' => 'BRUNEI-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0939', 'keturunan' => 'RUNGUS-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0940', 'keturunan' => 'BISAYA-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0941', 'keturunan' => 'IDAHAN-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0942', 'keturunan' => 'IRANUN-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0943', 'keturunan' => 'KEDAYAN-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0944', 'keturunan' => 'SUNGAI-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0945', 'keturunan' => 'LUNDAYEH-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0946', 'keturunan' => 'SULUK-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0947', 'keturunan' => 'TIDUNG-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0948', 'keturunan' => 'BOLONGAN-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '0949', 'keturunan' => 'BALABAK-SINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1000', 'keturunan' => 'BUMIPUTERA SARAWAK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1001', 'keturunan' => 'MELAYU SARAWAK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1002', 'keturunan' => 'MELANAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1003', 'keturunan' => 'KEDAYAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1004', 'keturunan' => 'IBAN ATAU SEA DAYAK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1005', 'keturunan' => 'BIDAYUH ATAU LAND DAYAK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1006', 'keturunan' => 'KAYAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1007', 'keturunan' => 'KENYAH', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1008', 'keturunan' => 'MURUT ATAU LUN BAWANG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1009', 'keturunan' => 'KELABIT', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1010', 'keturunan' => 'PUNAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1011', 'keturunan' => 'PENAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1012', 'keturunan' => 'TRING', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1013', 'keturunan' => 'LOGAT', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1014', 'keturunan' => 'BAH MALI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1015', 'keturunan' => 'NAROM', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1016', 'keturunan' => 'BAKONG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1017', 'keturunan' => 'MIRIEK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1018', 'keturunan' => 'DALI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1019', 'keturunan' => 'SEGAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1101', 'keturunan' => 'BISAYA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1102', 'keturunan' => 'BERAWAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1103', 'keturunan' => 'BELOT', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1104', 'keturunan' => 'BHUKET ATAU UKIT', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1105', 'keturunan' => 'BALAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1106', 'keturunan' => 'BATANG AI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1107', 'keturunan' => 'BATU ELAH', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1108', 'keturunan' => 'BAKETAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1109', 'keturunan' => 'BINTULU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1110', 'keturunan' => 'BADENG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1111', 'keturunan' => 'DUSUN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1112', 'keturunan' => 'JAGOI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1113', 'keturunan' => 'LAKIPUT', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1114', 'keturunan' => 'KAJANG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1115', 'keturunan' => 'KEJAMAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1116', 'keturunan' => 'KANOWIT', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1117', 'keturunan' => 'LIRONG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1118', 'keturunan' => 'LEMANAK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1119', 'keturunan' => 'LAHANAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1120', 'keturunan' => 'LISUM ATAU LUGUM', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1121', 'keturunan' => 'MATU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1122', 'keturunan' => 'MEMALOH', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1123', 'keturunan' => 'MELIKIN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1124', 'keturunan' => 'MELAING', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1125', 'keturunan' => 'NGORIK ATAU MUREK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1126', 'keturunan' => 'MENONDO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1127', 'keturunan' => 'JAMOK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1128', 'keturunan' => 'SEBOP', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1129', 'keturunan' => 'SEDUAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1130', 'keturunan' => 'SEKAPAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1131', 'keturunan' => 'SEGALANG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1132', 'keturunan' => 'SIHAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1133', 'keturunan' => 'SEPING', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1134', 'keturunan' => 'SARIBAS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1135', 'keturunan' => 'SEBUYAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1136', 'keturunan' => 'SKRANG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1137', 'keturunan' => 'SABAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1138', 'keturunan' => 'SELAKAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1139', 'keturunan' => 'SELAKO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1140', 'keturunan' => 'TAGAL', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1141', 'keturunan' => 'TABUN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1142', 'keturunan' => 'TUTONG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1143', 'keturunan' => 'TANJONG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1144', 'keturunan' => 'TATAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1145', 'keturunan' => 'TAUP', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1146', 'keturunan' => 'UKIT', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1147', 'keturunan' => 'UNKOP', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1148', 'keturunan' => 'ULU AI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1149', 'keturunan' => 'TORAJA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1150', 'keturunan' => 'TIMOR', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1151', 'keturunan' => 'MENADO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1152', 'keturunan' => 'MANURA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1153', 'keturunan' => 'BATAK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1154', 'keturunan' => 'PATHAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1155', 'keturunan' => 'TONGANS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1200', 'keturunan' => 'ORANG ASLI (SEMENANJUNG)', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1201', 'keturunan' => 'JAKUN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1202', 'keturunan' => 'NEGRITO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1203', 'keturunan' => 'SAKAI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1204', 'keturunan' => 'SEMAI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1205', 'keturunan' => 'SEMALAI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1206', 'keturunan' => 'TEMIAR', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1207', 'keturunan' => 'SENOI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1300', 'keturunan' => 'LAIN-LAIN ASIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1301', 'keturunan' => 'ARAB', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1302', 'keturunan' => 'BURMESE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1303', 'keturunan' => 'EURASIAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1304', 'keturunan' => 'FIJIAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1305', 'keturunan' => 'FILIPINO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1306', 'keturunan' => 'GURKHA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1307', 'keturunan' => 'JAPANESE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1308', 'keturunan' => 'KHMER', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1309', 'keturunan' => 'KOREAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1310', 'keturunan' => 'MALTESE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1311', 'keturunan' => 'PORTUGESE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1312', 'keturunan' => 'THAI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1313', 'keturunan' => 'VIETNAMESE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1314', 'keturunan' => 'IRANIAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1315', 'keturunan' => 'AFGHAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1316', 'keturunan' => 'CAUCASIAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1317', 'keturunan' => 'KYRGYZ', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1318', 'keturunan' => 'UBIAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1319', 'keturunan' => 'UZBEKISTAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1320', 'keturunan' => 'AZERBAIJAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1321', 'keturunan' => 'SIAM', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1322', 'keturunan' => 'KAZAKHSTAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1323', 'keturunan' => 'TAJIKISTAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1324', 'keturunan' => 'PEOPLES REPUBLIC OF CHINA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1325', 'keturunan' => 'SINGAPURA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1400', 'keturunan' => 'EUROPEAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1401', 'keturunan' => 'BRITISH', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1402', 'keturunan' => 'ALGERIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1403', 'keturunan' => 'ANTIGUA-BARBUDA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1404', 'keturunan' => 'AUSTRALIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1405', 'keturunan' => 'ANGOLA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1406', 'keturunan' => 'ARGENTINA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1407', 'keturunan' => 'ALBANIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1408', 'keturunan' => 'AUSTRIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1410', 'keturunan' => 'MIDDLE AFRICA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1411', 'keturunan' => 'SOUTH AFRICA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1412', 'keturunan' => 'BAHRAIN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1413', 'keturunan' => 'BAHAMAS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1414', 'keturunan' => 'BARBADOS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1415', 'keturunan' => 'BELIZE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1416', 'keturunan' => 'BOTSWANA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1418', 'keturunan' => 'BENIN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1419', 'keturunan' => 'BHUTAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1420', 'keturunan' => 'BOLIVIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1421', 'keturunan' => 'BRAZIL', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1422', 'keturunan' => 'BURUNDI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1423', 'keturunan' => 'BULGARIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1424', 'keturunan' => 'BELGIUM', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1425', 'keturunan' => 'BELARUS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1427', 'keturunan' => 'BOSNIA-HERZEGOVINA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1428', 'keturunan' => 'CAMEROON', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1429', 'keturunan' => 'CHAD', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1430', 'keturunan' => 'CANADA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1431', 'keturunan' => 'CYPRUS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1432', 'keturunan' => 'CAPE VERDE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1433', 'keturunan' => 'CROTIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1434', 'keturunan' => 'CHILE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1435', 'keturunan' => 'COLOMBIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1436', 'keturunan' => 'COMOROS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1437', 'keturunan' => 'COSTA-RICA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1438', 'keturunan' => 'CUBA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1439', 'keturunan' => 'DJBOUTI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1440', 'keturunan' => 'DOMINICA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1441', 'keturunan' => 'DAHOMEY', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1442', 'keturunan' => 'DENMARK', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1443', 'keturunan' => 'EQUADOR', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1444', 'keturunan' => 'EL SALVADOR', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1445', 'keturunan' => 'EQUATORIAL GUINEA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1446', 'keturunan' => 'ETOPIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1448', 'keturunan' => 'FRANCE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1449', 'keturunan' => 'FINLAND', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1451', 'keturunan' => 'GABON', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1452', 'keturunan' => 'GAMBIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1453', 'keturunan' => 'GUINEA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1454', 'keturunan' => 'GUINEA-BISSAU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1455', 'keturunan' => 'GHANA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1456', 'keturunan' => 'GRENADA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1457', 'keturunan' => 'GUYANA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1458', 'keturunan' => 'GUATEMALA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1459', 'keturunan' => 'GREECE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1460', 'keturunan' => 'GERMANY', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1461', 'keturunan' => 'HAITI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1462', 'keturunan' => 'HONDURAS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1463', 'keturunan' => 'HUNGARY', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1464', 'keturunan' => 'HONG KONG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1466', 'keturunan' => 'IRAQ', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1467', 'keturunan' => 'IVORY COAST', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1468', 'keturunan' => 'ISRAEL', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1469', 'keturunan' => 'IRELAND', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1470', 'keturunan' => 'ITALY', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1471', 'keturunan' => 'ICELAND', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1472', 'keturunan' => 'JORDAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1473', 'keturunan' => 'JAMAICA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1475', 'keturunan' => 'KUWAIT', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1476', 'keturunan' => 'KENYA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1477', 'keturunan' => 'KIRIBATI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1479', 'keturunan' => 'KOREA(UTARA)', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1480', 'keturunan' => 'KEMBOJA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1481', 'keturunan' => 'LEBANON', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1482', 'keturunan' => 'LIBYA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1483', 'keturunan' => 'LESOTHO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1484', 'keturunan' => 'LAOS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1485', 'keturunan' => 'LIBERIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1486', 'keturunan' => 'LUXEMBOURG', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1487', 'keturunan' => 'MALI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1488', 'keturunan' => 'MALDIVES', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1489', 'keturunan' => 'MAURITANIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1490', 'keturunan' => 'MOROCCO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1491', 'keturunan' => 'MALAWI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1493', 'keturunan' => 'MADAGASCAR', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1494', 'keturunan' => 'MAURITIUS', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1495', 'keturunan' => 'MEXICO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1496', 'keturunan' => 'MOZAMBIQUE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1497', 'keturunan' => 'MONGOLIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1498', 'keturunan' => 'MESIR', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1499', 'keturunan' => 'MYANMAR', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1500', 'keturunan' => 'LAIN-LAIN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1501', 'keturunan' => 'NAMIBIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1502', 'keturunan' => 'NAURU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1503', 'keturunan' => 'NEW ZEALAND', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1504', 'keturunan' => 'NIGERIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1505', 'keturunan' => 'NEPAL', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1506', 'keturunan' => 'NICARAGUA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1507', 'keturunan' => 'NETHERLAND', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1508', 'keturunan' => 'NORWAY', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1509', 'keturunan' => 'OMAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1510', 'keturunan' => 'PAPUA NEW GUINEA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1511', 'keturunan' => 'PALESTIN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1512', 'keturunan' => 'PANAMA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1513', 'keturunan' => 'PARAGUAY', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1514', 'keturunan' => 'PERU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1515', 'keturunan' => 'POLAND', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1516', 'keturunan' => 'REPUBLIC OF INDIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1517', 'keturunan' => 'QATAR', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1518', 'keturunan' => 'ROMANIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1519', 'keturunan' => 'RWANDA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1520', 'keturunan' => 'REPUBLIK CZECH', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1521', 'keturunan' => 'REPUBLIK SLOVAKIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1522', 'keturunan' => 'SENEGAL', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1523', 'keturunan' => 'SIERRA LEONE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1524', 'keturunan' => 'SOMALIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1525', 'keturunan' => 'SUDAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1526', 'keturunan' => 'SYRIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1527', 'keturunan' => 'ST.LUCIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1528', 'keturunan' => 'ST.VINCENT', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1529', 'keturunan' => 'SYCHELLES', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1530', 'keturunan' => 'SOLOMON ISLAND', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1531', 'keturunan' => 'SRI LANKA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1532', 'keturunan' => 'SWAZILAND', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1533', 'keturunan' => 'SAMOA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1534', 'keturunan' => 'SAO TOME & PRINCIPE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1535', 'keturunan' => 'SURINAM', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1536', 'keturunan' => 'SAMOA BARAT', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1537', 'keturunan' => 'SWEDEN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1538', 'keturunan' => 'SPAIN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1539', 'keturunan' => 'SWITZERLAND', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1540', 'keturunan' => 'TUNISIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1541', 'keturunan' => 'TURKEY', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1542', 'keturunan' => 'TANZANIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1543', 'keturunan' => 'TONGA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1544', 'keturunan' => 'TRINIDAD & TOBAGO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1545', 'keturunan' => 'TUVALI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1547', 'keturunan' => 'TOGO', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1548', 'keturunan' => 'TAIWAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1549', 'keturunan' => 'UGANDA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1550', 'keturunan' => 'UNITED ARAB EMIRATES', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1551', 'keturunan' => 'UPPER VOLTA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1552', 'keturunan' => 'URUGUAY', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1553', 'keturunan' => 'RUSSIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1554', 'keturunan' => 'UKRAINE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1555', 'keturunan' => 'UNITED STATES', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1556', 'keturunan' => 'VANUATU', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1557', 'keturunan' => 'VENEZUELA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1559', 'keturunan' => 'YEMEN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1560', 'keturunan' => 'YUGOSLAVIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1561', 'keturunan' => 'MACEDONIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1562', 'keturunan' => 'ZAIRE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1563', 'keturunan' => 'ZAMBIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1564', 'keturunan' => 'ZIMBABWE', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1565', 'keturunan' => 'SLOVENIA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1566', 'keturunan' => 'TURKMENISTAN', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '1568', 'keturunan' => 'DUTCH', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '9998', 'keturunan' => 'MAKLUMAT TIDAK DIPEROLEHI', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['kod_keturunan' => '9999', 'keturunan' => 'MAKLUMAT TIADA', 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')]
            ]);
        }
    }
}
