<?php

namespace Database\Seeders;

use App\Models\Constant\Parlimen;
use Illuminate\Database\Seeder;

class ParlimenSeeder extends Seeder
{
    public function run()
    {
        // check if parlimen is empty
        if (Parlimen::count() == 0) {

            Parlimen::insert([
                ['id' => 1, 'kod_parlimen' => '001', 'keterangan' => 'PADANG BESAR', 'id_negeri' => 9, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 2, 'kod_parlimen' => '002', 'keterangan' => 'KANGAR', 'id_negeri' => 9, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 3, 'kod_parlimen' => '003', 'keterangan' => 'ARAU', 'id_negeri' => 9, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 4, 'kod_parlimen' => '004', 'keterangan' => 'LANGKAWI', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 5, 'kod_parlimen' => '005', 'keterangan' => 'JERLUN', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 6, 'kod_parlimen' => '006', 'keterangan' => 'KUBANG PASU', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 7, 'kod_parlimen' => '007', 'keterangan' => 'PADANG TERAP', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 8, 'kod_parlimen' => '008', 'keterangan' => 'POKOK SENA', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 9, 'kod_parlimen' => '009', 'keterangan' => 'ALOR SETAR', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 10, 'kod_parlimen' => '010', 'keterangan' => 'KUALA KEDAH', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 11, 'kod_parlimen' => '011', 'keterangan' => 'PENDANG', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 12, 'kod_parlimen' => '012', 'keterangan' => 'JERAI', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 13, 'kod_parlimen' => '013', 'keterangan' => 'SIK', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 14, 'kod_parlimen' => '014', 'keterangan' => 'MERBOK', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 15, 'kod_parlimen' => '015', 'keterangan' => 'SUNGAI PETANI', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 16, 'kod_parlimen' => '016', 'keterangan' => 'BALING', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 17, 'kod_parlimen' => '017', 'keterangan' => 'PADANG SERAI', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 18, 'kod_parlimen' => '018', 'keterangan' => 'KULIM-BANDAR BAHARU', 'id_negeri' => 2, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 19, 'kod_parlimen' => '019', 'keterangan' => 'TUMPAT', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 20, 'kod_parlimen' => '020', 'keterangan' => 'PENGKALAN CHEPA', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 21, 'kod_parlimen' => '021', 'keterangan' => 'KOTA BHARU', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 22, 'kod_parlimen' => '022', 'keterangan' => 'PASIR MAS', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 23, 'kod_parlimen' => '023', 'keterangan' => 'RANTAU PANJANG', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 24, 'kod_parlimen' => '024', 'keterangan' => 'KUBANG KERIAN', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 25, 'kod_parlimen' => '025', 'keterangan' => 'BACHOK', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 26, 'kod_parlimen' => '026', 'keterangan' => 'KETEREH', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 27, 'kod_parlimen' => '027', 'keterangan' => 'TANAH MERAH', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 28, 'kod_parlimen' => '028', 'keterangan' => 'PASIR PUTEH', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 29, 'kod_parlimen' => '029', 'keterangan' => 'MACHANG', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 30, 'kod_parlimen' => '030', 'keterangan' => 'JELI', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 31, 'kod_parlimen' => '031', 'keterangan' => 'KUALA KRAI', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 32, 'kod_parlimen' => '032', 'keterangan' => 'GUA MUSANG', 'id_negeri' => 3, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 33, 'kod_parlimen' => '033', 'keterangan' => 'BESUT', 'id_negeri' => 11, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 34, 'kod_parlimen' => '034', 'keterangan' => 'SETIU', 'id_negeri' => 11, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 35, 'kod_parlimen' => '035', 'keterangan' => 'KUALA NERUS', 'id_negeri' => 11, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 36, 'kod_parlimen' => '036', 'keterangan' => 'KUALA TERENGGANU', 'id_negeri' => 11, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 37, 'kod_parlimen' => '037', 'keterangan' => 'MARANG', 'id_negeri' => 11, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 38, 'kod_parlimen' => '038', 'keterangan' => 'HULU TERENGGANU', 'id_negeri' => 11, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 39, 'kod_parlimen' => '039', 'keterangan' => 'DUNGUN', 'id_negeri' => 11, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 40, 'kod_parlimen' => '040', 'keterangan' => 'KEMAMAN', 'id_negeri' => 11, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 41, 'kod_parlimen' => '041', 'keterangan' => 'KEPALA BATAS', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 42, 'kod_parlimen' => '042', 'keterangan' => 'TASEK GELUGOR', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 43, 'kod_parlimen' => '043', 'keterangan' => 'BAGAN', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 44, 'kod_parlimen' => '044', 'keterangan' => 'PERMATANG PAUH', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 45, 'kod_parlimen' => '045', 'keterangan' => 'BUKIT MERTAJAM', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 46, 'kod_parlimen' => '046', 'keterangan' => 'BATU KAWAN', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 47, 'kod_parlimen' => '047', 'keterangan' => 'NIBONG TEBAL', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 48, 'kod_parlimen' => '048', 'keterangan' => 'BUKIT BENDERA', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 49, 'kod_parlimen' => '049', 'keterangan' => 'TANJONG', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 50, 'kod_parlimen' => '050', 'keterangan' => 'JELUTONG', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 51, 'kod_parlimen' => '051', 'keterangan' => 'BUKIT GELUGOR', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 52, 'kod_parlimen' => '052', 'keterangan' => 'BAYAN BARU', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 53, 'kod_parlimen' => '053', 'keterangan' => 'BALIK PULAU', 'id_negeri' => 7, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 54, 'kod_parlimen' => '054', 'keterangan' => 'GERIK', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 55, 'kod_parlimen' => '055', 'keterangan' => 'LENGGONG', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 56, 'kod_parlimen' => '056', 'keterangan' => 'LARUT', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 57, 'kod_parlimen' => '057', 'keterangan' => 'PARIT BUNTAR', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 58, 'kod_parlimen' => '058', 'keterangan' => 'BAGAN SERAI', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 59, 'kod_parlimen' => '059', 'keterangan' => 'BUKIT GANTANG', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 60, 'kod_parlimen' => '060', 'keterangan' => 'TAIPING', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 61, 'kod_parlimen' => '061', 'keterangan' => 'PADANG RENGAS', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 62, 'kod_parlimen' => '062', 'keterangan' => 'SUNGAI SIPUT', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 63, 'kod_parlimen' => '063', 'keterangan' => 'TAMBUN', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 64, 'kod_parlimen' => '064', 'keterangan' => 'IPOH TIMOR', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 65, 'kod_parlimen' => '065', 'keterangan' => 'IPOH BARAT', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 66, 'kod_parlimen' => '066', 'keterangan' => 'BATU GAJAH', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 67, 'kod_parlimen' => '067', 'keterangan' => 'KUALA KANGSAR', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 68, 'kod_parlimen' => '068', 'keterangan' => 'BERUAS', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 69, 'kod_parlimen' => '069', 'keterangan' => 'PARIT', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 70, 'kod_parlimen' => '070', 'keterangan' => 'KAMPAR', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 71, 'kod_parlimen' => '071', 'keterangan' => 'GOPENG', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 72, 'kod_parlimen' => '072', 'keterangan' => 'TAPAH', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 73, 'kod_parlimen' => '073', 'keterangan' => 'PASIR SALAK', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 74, 'kod_parlimen' => '074', 'keterangan' => 'LUMUT', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 75, 'kod_parlimen' => '075', 'keterangan' => 'BAGAN DATUK', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 76, 'kod_parlimen' => '076', 'keterangan' => 'TELUK INTAN', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 77, 'kod_parlimen' => '077', 'keterangan' => 'TANJONG MALIM', 'id_negeri' => 8, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 78, 'kod_parlimen' => '078', 'keterangan' => 'CAMERON HIGHLANDS', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 79, 'kod_parlimen' => '079', 'keterangan' => 'LIPIS', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 80, 'kod_parlimen' => '080', 'keterangan' => 'RAUB', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 81, 'kod_parlimen' => '081', 'keterangan' => 'JERANTUT', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 82, 'kod_parlimen' => '082', 'keterangan' => 'INDERA MAHKOTA', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 83, 'kod_parlimen' => '083', 'keterangan' => 'KUANTAN', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 84, 'kod_parlimen' => '084', 'keterangan' => 'PAYA BESAR', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 85, 'kod_parlimen' => '085', 'keterangan' => 'PEKAN', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 86, 'kod_parlimen' => '086', 'keterangan' => 'MARAN', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 87, 'kod_parlimen' => '087', 'keterangan' => 'KUALA KRAU', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 88, 'kod_parlimen' => '088', 'keterangan' => 'TEMERLOH', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 89, 'kod_parlimen' => '089', 'keterangan' => 'BENTONG', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 90, 'kod_parlimen' => '090', 'keterangan' => 'BERA', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 91, 'kod_parlimen' => '091', 'keterangan' => 'ROMPIN', 'id_negeri' => 6, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 92, 'kod_parlimen' => '092', 'keterangan' => 'SABAK BERNAM', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 93, 'kod_parlimen' => '093', 'keterangan' => 'SUNGAI BESAR', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 94, 'kod_parlimen' => '094', 'keterangan' => 'HULU SELANGOR', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 95, 'kod_parlimen' => '095', 'keterangan' => 'TANJONG KARANG', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 96, 'kod_parlimen' => '096', 'keterangan' => 'KUALA SELANGOR', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 97, 'kod_parlimen' => '097', 'keterangan' => 'SELAYANG', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 98, 'kod_parlimen' => '098', 'keterangan' => 'GOMBAK', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 99, 'kod_parlimen' => '099', 'keterangan' => 'AMPANG', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 100, 'kod_parlimen' => '100', 'keterangan' => 'PANDAN', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 101, 'kod_parlimen' => '101', 'keterangan' => 'HULU LANGAT', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 102, 'kod_parlimen' => '102', 'keterangan' => 'BANGI', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 103, 'kod_parlimen' => '103', 'keterangan' => 'PUCHONG', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 104, 'kod_parlimen' => '104', 'keterangan' => 'SUBANG', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 105, 'kod_parlimen' => '105', 'keterangan' => 'PETALING JAYA', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 106, 'kod_parlimen' => '106', 'keterangan' => 'DAMANSARA', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 107, 'kod_parlimen' => '107', 'keterangan' => 'SUNGAI BULOH', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 108, 'kod_parlimen' => '108', 'keterangan' => 'SHAH ALAM', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 109, 'kod_parlimen' => '109', 'keterangan' => 'KAPAR', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 110, 'kod_parlimen' => '110', 'keterangan' => 'KLANG', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 111, 'kod_parlimen' => '111', 'keterangan' => 'KOTA RAJA', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 112, 'kod_parlimen' => '112', 'keterangan' => 'KUALA LANGAT', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 113, 'kod_parlimen' => '113', 'keterangan' => 'SEPANG', 'id_negeri' => 10, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 114, 'kod_parlimen' => '114', 'keterangan' => 'KEPONG', 'id_negeri' => 14, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 115, 'kod_parlimen' => '115', 'keterangan' => 'BATU', 'id_negeri' => 14, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 116, 'kod_parlimen' => '116', 'keterangan' => 'WANGSA MAJU', 'id_negeri' => 14, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 117, 'kod_parlimen' => '117', 'keterangan' => 'SEGAMBUT', 'id_negeri' => 14, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 118, 'kod_parlimen' => '118', 'keterangan' => 'SETIAWANGSA', 'id_negeri' => 14, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 119, 'kod_parlimen' => '119', 'keterangan' => 'TITIWANGSA', 'id_negeri' => 14, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 120, 'kod_parlimen' => '120', 'keterangan' => 'BUKIT BINTANG', 'id_negeri' => 14, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 121, 'kod_parlimen' => '121', 'keterangan' => 'LEMBAH PANTAI', 'id_negeri' => 14, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 122, 'kod_parlimen' => '122', 'keterangan' => 'SEPUTEH', 'id_negeri' => 14, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 123, 'kod_parlimen' => '123', 'keterangan' => 'CHERAS', 'id_negeri' => 14, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 124, 'kod_parlimen' => '124', 'keterangan' => 'BANDAR TUN RAZAK', 'id_negeri' => 14, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 125, 'kod_parlimen' => '125', 'keterangan' => 'PUTRAJAYA', 'id_negeri' => 16, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 126, 'kod_parlimen' => '126', 'keterangan' => 'JELEBU', 'id_negeri' => 5, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 127, 'kod_parlimen' => '127', 'keterangan' => 'JEMPOL', 'id_negeri' => 5, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 128, 'kod_parlimen' => '128', 'keterangan' => 'SEREMBAN', 'id_negeri' => 5, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 129, 'kod_parlimen' => '129', 'keterangan' => 'KUALA PILAH', 'id_negeri' => 5, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 130, 'kod_parlimen' => '130', 'keterangan' => 'RASAH', 'id_negeri' => 5, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 131, 'kod_parlimen' => '131', 'keterangan' => 'REMBAU', 'id_negeri' => 5, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 132, 'kod_parlimen' => '132', 'keterangan' => 'PORT DICKSON', 'id_negeri' => 5, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 133, 'kod_parlimen' => '133', 'keterangan' => 'TAMPIN', 'id_negeri' => 5, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 134, 'kod_parlimen' => '134', 'keterangan' => 'MASJID TANAH', 'id_negeri' => 4, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 135, 'kod_parlimen' => '135', 'keterangan' => 'ALOR GAJAH', 'id_negeri' => 4, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 136, 'kod_parlimen' => '136', 'keterangan' => 'TANGGA BATU', 'id_negeri' => 4, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 137, 'kod_parlimen' => '137', 'keterangan' => 'HANG TUAH JAYA', 'id_negeri' => 4, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 138, 'kod_parlimen' => '138', 'keterangan' => 'KOTA MELAKA', 'id_negeri' => 4, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 139, 'kod_parlimen' => '139', 'keterangan' => 'JASIN', 'id_negeri' => 4, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 140, 'kod_parlimen' => '140', 'keterangan' => 'SEGAMAT', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 141, 'kod_parlimen' => '141', 'keterangan' => 'SEKIJANG', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 142, 'kod_parlimen' => '142', 'keterangan' => 'LABIS', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 143, 'kod_parlimen' => '143', 'keterangan' => 'PAGOH', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 144, 'kod_parlimen' => '144', 'keterangan' => 'LEDANG', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 145, 'kod_parlimen' => '145', 'keterangan' => 'BAKRI', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 146, 'kod_parlimen' => '146', 'keterangan' => 'MUAR', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 147, 'kod_parlimen' => '147', 'keterangan' => 'PARIT SULONG', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 148, 'kod_parlimen' => '148', 'keterangan' => 'AYER HITAM', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 149, 'kod_parlimen' => '149', 'keterangan' => 'SRI GADING', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 150, 'kod_parlimen' => '150', 'keterangan' => 'BATU PAHAT', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 151, 'kod_parlimen' => '151', 'keterangan' => 'SIMPANG RENGGAM', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 152, 'kod_parlimen' => '152', 'keterangan' => 'KLUANG', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 153, 'kod_parlimen' => '153', 'keterangan' => 'SEMBRONG', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 154, 'kod_parlimen' => '154', 'keterangan' => 'MERSING', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 155, 'kod_parlimen' => '155', 'keterangan' => 'TENGGARA', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 156, 'kod_parlimen' => '156', 'keterangan' => 'KOTA TINGGI', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 157, 'kod_parlimen' => '157', 'keterangan' => 'PENGERANG', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 158, 'kod_parlimen' => '158', 'keterangan' => 'TEBRAU', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 159, 'kod_parlimen' => '159', 'keterangan' => 'PASIR GUDANG', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 160, 'kod_parlimen' => '160', 'keterangan' => 'JOHOR BAHRU', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 161, 'kod_parlimen' => '161', 'keterangan' => 'PULAI', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 162, 'kod_parlimen' => '162', 'keterangan' => 'ISKANDAR PUTERI', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 163, 'kod_parlimen' => '163', 'keterangan' => 'KULAI', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 164, 'kod_parlimen' => '164', 'keterangan' => 'PONTIAN', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 165, 'kod_parlimen' => '165', 'keterangan' => 'TANJUNG PIAI', 'id_negeri' => 1, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 166, 'kod_parlimen' => '166', 'keterangan' => 'LABUAN', 'id_negeri' => 15, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 167, 'kod_parlimen' => '167', 'keterangan' => 'KUDAT', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 168, 'kod_parlimen' => '168', 'keterangan' => 'KOTA MARUDU', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 169, 'kod_parlimen' => '169', 'keterangan' => 'KOTA BELUD', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 170, 'kod_parlimen' => '170', 'keterangan' => 'TUARAN', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 171, 'kod_parlimen' => '171', 'keterangan' => 'SEPANGGAR', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 172, 'kod_parlimen' => '172', 'keterangan' => 'KOTA KINABALU', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 173, 'kod_parlimen' => '173', 'keterangan' => 'PUTATAN', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 174, 'kod_parlimen' => '174', 'keterangan' => 'PENAMPANG', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 175, 'kod_parlimen' => '175', 'keterangan' => 'PAPAR', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 176, 'kod_parlimen' => '176', 'keterangan' => 'KIMANIS', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 177, 'kod_parlimen' => '177', 'keterangan' => 'BEAUFORT', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 178, 'kod_parlimen' => '178', 'keterangan' => 'SIPITANG', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 179, 'kod_parlimen' => '179', 'keterangan' => 'RANAU', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 180, 'kod_parlimen' => '180', 'keterangan' => 'KENINGAU', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 181, 'kod_parlimen' => '181', 'keterangan' => 'TENOM', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 182, 'kod_parlimen' => '182', 'keterangan' => 'PENSIANGAN', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 183, 'kod_parlimen' => '183', 'keterangan' => 'BELURAN', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 184, 'kod_parlimen' => '184', 'keterangan' => 'LIBARAN', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 185, 'kod_parlimen' => '185', 'keterangan' => 'BATU SAPI', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 186, 'kod_parlimen' => '186', 'keterangan' => 'SANDAKAN', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 187, 'kod_parlimen' => '187', 'keterangan' => 'KINABATANGAN', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 188, 'kod_parlimen' => '188', 'keterangan' => 'SILAM', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 189, 'kod_parlimen' => '189', 'keterangan' => 'SEMPORNA', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 190, 'kod_parlimen' => '190', 'keterangan' => 'TAWAU', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 191, 'kod_parlimen' => '191', 'keterangan' => 'KALABAKAN', 'id_negeri' => 12, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 192, 'kod_parlimen' => '192', 'keterangan' => 'MAS GADING', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 193, 'kod_parlimen' => '193', 'keterangan' => 'SANTUBONG', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 194, 'kod_parlimen' => '194', 'keterangan' => 'PETRA JAYA', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 195, 'kod_parlimen' => '195', 'keterangan' => 'BANDAR KUCHING', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 196, 'kod_parlimen' => '196', 'keterangan' => 'STAMPIN', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 197, 'kod_parlimen' => '197', 'keterangan' => 'KOTA SAMARAHAN', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 198, 'kod_parlimen' => '198', 'keterangan' => 'PUNCAK BORNEO', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 199, 'kod_parlimen' => '199', 'keterangan' => 'SERIAN', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 200, 'kod_parlimen' => '200', 'keterangan' => 'BATANG SADONG', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 201, 'kod_parlimen' => '201', 'keterangan' => 'BATANG LUPAR', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 202, 'kod_parlimen' => '202', 'keterangan' => 'SRI AMAN', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 203, 'kod_parlimen' => '203', 'keterangan' => 'LUBOK ANTU', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 204, 'kod_parlimen' => '204', 'keterangan' => 'BETONG', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 205, 'kod_parlimen' => '205', 'keterangan' => 'SARATOK', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 206, 'kod_parlimen' => '206', 'keterangan' => 'TANJONG MANIS', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 207, 'kod_parlimen' => '207', 'keterangan' => 'IGAN', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 208, 'kod_parlimen' => '208', 'keterangan' => 'SARIKEI', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 209, 'kod_parlimen' => '209', 'keterangan' => 'JULAU', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 210, 'kod_parlimen' => '210', 'keterangan' => 'KANOWIT', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 211, 'kod_parlimen' => '211', 'keterangan' => 'LANANG', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 212, 'kod_parlimen' => '212', 'keterangan' => 'SIBU', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 213, 'kod_parlimen' => '213', 'keterangan' => 'MUKAH', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 214, 'kod_parlimen' => '214', 'keterangan' => 'SELANGAU', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 215, 'kod_parlimen' => '215', 'keterangan' => 'KAPIT', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 216, 'kod_parlimen' => '216', 'keterangan' => 'HULU RAJANG', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 217, 'kod_parlimen' => '217', 'keterangan' => 'BINTULU', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 218, 'kod_parlimen' => '218', 'keterangan' => 'SIBUTI', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 219, 'kod_parlimen' => '219', 'keterangan' => 'MIRI', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 220, 'kod_parlimen' => '220', 'keterangan' => 'BARAM', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 221, 'kod_parlimen' => '221', 'keterangan' => 'LIMBANG', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
                ['id' => 222, 'kod_parlimen' => '222', 'keterangan' => 'LAWAS', 'id_negeri' => 13, 'status' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],

            ]);
        }
    }
}
